services:
  react:
    image: mirana-react:latest
    networks:
      - dev-network
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - api

  api:
    image: mirana-api:latest
    restart: always
    networks:
      - dev-network
    ports:
      - "5000:5000"
    environment:
      ConnectionStrings__Database: "Server=db;Database=MrnDataBase;User Id=sa;Password=myStrongPassword123;Encrypt=True;TrustServerCertificate=True"
    depends_on:
      - db

  # admin:
  #   image: mirana-admin:latest
  #   restart: always
  #   networks:
  #     - dev-network
  #   ports:
  #     - "5001:5000"
  #   environment:
  #     BaseAddress: "http://api:5000"
  #     ConnectionStrings__Database: "Server=db;Database=MrnDataBaseAdmin;User Id=sa;Password=myStrongPassword123;Encrypt=True;TrustServerCertificate=True"
  #   depends_on:
  #     - db
  #     - api

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    networks:
      - dev-network
    environment:
      MSSQL_SA_PASSWORD: myStrongPassword123
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"

networks:
  dev-network:
    driver: bridge
