FROM node:20.19.0-alpine AS build

WORKDIR /app

COPY ./src/frontend/miranaSolution.WebApp/package.json \
  ./src/frontend/miranaSolution.WebApp/yarn.lock ./

RUN yarn

ENV GENERATE_SOURCEMAP=false
ENV NODE_OPTIONS=--max-old-space-size=16384

COPY ./src/frontend/miranaSolution.WebApp/ ./

RUN yarn build

###
FROM nginx:1.26.3-alpine

COPY --from=build /app/dist/ /usr/share/nginx/html/

COPY ./react.nginx.conf /etc/nginx/nginx.conf

EXPOSE 80